-- 1. Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
  Dept_Name VARCHAR2(20),
  Dept_Num  NUMBER CONSTRAINT DEPT_PK PRIMARY KEY,
  MGR_SSN   VARCHAR2(9)
);

-- 2. Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
  EName        VARCHAR2(30),
  SSN_No       VARCHAR2(9) CONSTRAINT EMP_PK PRIMARY KEY,
  DoB          DATE,
  City         VARCHAR2(20),
  Sex          CHAR(1),
  Salary       NUMBER(8,2),
  Manager_SSN  VARCHAR2(9),
  Dept_No      NUMBER CONSTRAINT EMP_DEPT_FK REFERENCES DEPARTMENT(Dept_Num)
);

-- 3. Create WORKS_ON table after EMPLOYEE exists
CREATE TABLE WORKS_ON (
  SSN_Num  VARCHAR2(9) CONSTRAINT WORKS_EMP_FK REFERENCES EMPLOYEE(SSN_No),
  Project  VARCHAR2(10),
  Hours    NUMBER(5,2),
  CONSTRAINT WORKS_PK PRIMARY KEY (SSN_Num, Project)
);
